sudo: true
dist: trusty

language: python
python: 3.6

install:
- pip install -r requirements.txt
- pip install coverage

jobs:
  include:
  - stage: build docker image and push to heroku
    script:
      - docker login --username=_ --password=$HEROKU_TOKEN registry.heroku.com
      - docker tag -t registry.heroku.com/$APP_NAME:latest
      - docker push registry.heroku.com/$APP_NAME:latest
  - stage: run tests
    script:
      - docker ps | grep -i $APP_NAME
      - coverage erase
      - coverage run --source=. -m unittest discover -s tests/
      - coverage report -m

env:
  global:
  - secure: fDtDxIjA43qG5pa0JPWrqwgXUPZeWw9PCmhpuppEBu6pExDqQmQWhIWPTt1W5XvyzKivue90U4HcQCgRqIJVQeoBQ/T+77LdotdVjs6bd59wclvUl2r1oRv/w8eM1cFPqh0MElqSsPeW7YHbbeRdEGNMgF1LS+uZ2b0onLMTQvZA6/o8wkHWkg+I7cgXIeLgqK89laB6kbD7Lsy5m7B0DZf5CuOJOWZoY6M5V/UjR502Uppl6/NwNCoz7A5HOTrZQGiVTB6QEAKCs3lUyslmmQx5HYFZGBnXgr1mCKyIFrLtxTX6Rbi+qMu8uiiAR3pa767YT/HLSJZ2gE4bW5Xp7ij7EEebnOR6GmTaQmYGcQT/VFMqz2RPz9XkzEewib44JeLtXMpemKBHIeB/UJmUV5PTUxP4ifmdbJCF5jFmeymU/atZH1B4dtZxKMTo5TqLxaoQ2sz7ZLGCh+GNuJpbiVd0LX9C3+IJzxKRaNPuZnfsGBKEGFKGkcSG9rXwj5EnQd/ZuwokGIToKItj6ah8ELWTGsRrOArM+HS8TfOcwXcTOD3ZNpBU0cUIu8tgJwhwqg4cBNrZnmIor66lOMWNW1Yom+ipEGTEpWy329yAdNq3+2pQOlU+1MwbwSET2Kc/e5LGYS+YtLKdiO9vd9Yctbt410P8tJy/wP3UZ3jSVSM=
  - secure: aOslbw9jSqsfNWQ7KjxeuvNKMJPtudoOU7OPF938GFjvSU5wWyCgrUD3wU2lzAekE3HMLNR8rE0cXu0Wbh8/JOZq2R3jOWCAyFkIqPXW96sjfnjsLCKFVzsuYrKJZfxJUSEHJLNDcG4cfxuGAV6dzIPwZpwgbQ8h8I1iQHzJ1pMj6q4BbGn4Tklt09DD8++5HpA7Qey7EolIotgrc9oHYnky4D4G58uY5OK0jW7eUogV1QlVzwvKjvYK0sliXY8C78DyYli0ma9RpuLC03pghmZZRikF4ZJWN217dP9g38tOJEEvUbO+F4eAnFdX/36H9rPnqAwqZQSQ+D5rRkldk+Gr7qYzXFDSrLJFben9E32R4OY07+81s+X41T5bWSCe4n2wgp41txlwFpsXOLk2eNPXD1o4JiLpKUitRAxBAFd5Hbu6BZJpijErnFb6mkXbaRPK47AYWERh8MfzLQErstJijGSfiDtoX701l8q0KBX7uvI7/Vl61qgp7iylvKi9xZu824SOkYb39a3duj+kFFVkgMPieWpB2Ul1SGR1P04NNye/U+emdzWzl0n5vmqLNAkpJEI9EZ6at6cdjYZ45sWos6sikPpl0ZZxvSrMoaVUu0H2p97GlqKTaERRliZOevSj5RdI8Xi0r8l+oJH3gNGEt3NSjKBtdzrcr9EvvYc=
