sudo: true
dist: trusty
language: python
python: 3.6
install:
- pip install -r requirements.txt
- pip install coverage
- pip install pylint
jobs:
  include:
  - stage: run tests
    script:
    - coverage erase
    - coverage run --source=. -m unittest discover -s tests/
    - pylint --output-format=text src/main.py
