sudo: true
dist: trusty

language: python
python: 3.6

install:
  - pip install -r requirements.txt
  - pip install coverage

jobs:
  include:
    - stage: build docker image
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t picapp-app-server .
      - docker images
      - docker tag picapp-app-server $DOCKER_USERNAME/picapp-app-server
      - docker push $DOCKER_USERNAME/picapp-app-server
    - stage: test
      script:
        - coverage erase
        - coverage run --source=. -m unittest discover -s tests/
        - coverage report -m

env:
  global:
  - secure: OQ2y0C4Hi/WWBUOHeRu6KBrLgOcr2prOgMEpvT2clVNrFMNMqcTW7HTcq9sbeFbR23n3hc3rv7yO2VM/s7Dxbqk5kAW0KbwBlj607WVS6HbF9rq84DRZKjINGtn5MDPJHrv8kp0g71WAvTJZWQwd7IbGQSc4SOxlGS8KH+Iz1/MqX6SGotIEXgLBrtP2wrtDRb26pTitunWTficiAXY2mFoCHsDlsKOT3qxcBYHl994R8UsbQaTCPE7dBSTYtdm97mbpMYxAE08OM55X/9KN13lGXKO4UjdvKMDZLxuvX7DDmYYAdi9iK8syd5OJRNwdHBqWt/dHJ9KxLNg8ORVjr8NhraA2csvyBHYMIAQXdvil4bFyH2y1K0nG6fFKhW6AnCeOGU/UDrwMfPBLHCgAa250wyaFQqb1Bg1N1OYfEoGhmx38zOAHjkpI1fADdG3l2LFdvk8uCw0i3979K6KW4p43NFyG//ouF9szNqm8KWf8VWOuvTqFTueOl5teoDD66EOd3UusSOmno6aNMDODYznbWzI+CwAYXwaZJomknrK2Eaw8xsB8reHwC0DKOj6hApkKKF3n2ce9S5xU3LcD21B35MMGU1jjADeLvaEAtqSW7PCr7pHFCRWBv2uobw/nv88cwxjIMEoDqhJYKC1mgypgx5Adn8sEsZgUy8wlcww=
  - secure: wE7+OLK1LWXwZeAwXKHxZiQMYPOg6aG8zB0Z6Z2VzpCqWr3bC634GJRYCNlM4bn+o30dQ9RQgBT7bFa2ieg5kKq0QNdjKM/a/RSw39PQ3YNY/E+wuBzYiJUrRuEWzNMOb3bcDb0eBiX7qIFzXqxnDsdM/EOe5ZrwCD4pjwnGvEit+hsSIO4Tok0CRdr08TgaCF00V8RyBJ6Cp+A8hUjupu+s9Bq9U/1CmLQM2ttvq3zp0Mtr17ojU/S3Hhp9e3xfjC5SSJ91v7w4t7CL1XE4qiN7n1c8vdL/x/aW/0LIFSD9QY4ZVKLVFLIVtH6JcqC/cYVoI/EyV5GPMsv5EMMeP7ZI8OZzSqsYWk9m2rjOlLEsWkuQQe1BBKPZ53y4kOkXT2qc+V5nZRJEMVAOt6sfJEFIIQqAhEZ4FiVXQRPt12LncUmY73bYeCCbEzv/Jq4B9yTGnugV6z0Pn3lIDM21s2ZGJbOUAXw5aF7XF1S9FbK/ClecZBN7OHPyiIJqrLbhnztM5DOCcuOQb4Wa/wGUqFBkdxx/vNEpYmQ0zX7+r1dCuLWuK8f81XGyCZF7YAiaBcF1ma0cadCqDBbcvRqmDCJMV+aJCIWKicyzXpl+6IAB62O8VdSGYP90WLrJec8qYad8AKaHt9WHGlBWrzOH1pRv2XUfDlLKXU2F5ypff+U=
