language: python
python:
  - 3.6

install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install pylint

script:
  - python -m unittest discover
  - behave
  - coverage erase
  - coverage run test_webapp.py && coverage html
  - pylint --output-format=text src/stories.py

after_success:
  - codecov