sudo: true
dist: trusty
language: python
python: 3.6
install:
- pip install -r requirements.txt
- pip install coverage
jobs:
  include:
  - stage: build docker image and push to heroku
    script:
    - docker login --username=_ --password=$HEROKU_TOKEN registry.heroku.com
    - docker build -t registry.heroku.com/$APP_NAME/web .
    - docker push registry.heroku.com/$APP_NAME/web
  - stage: run tests
    script:
    - docker ps | grep -i $APP_NAME
    - coverage erase
    - coverage run --source=. -m unittest discover -s tests/
    - coverage report -m
env:
  global:
  - secure: aOslbw9jSqsfNWQ7KjxeuvNKMJPtudoOU7OPF938GFjvSU5wWyCgrUD3wU2lzAekE3HMLNR8rE0cXu0Wbh8/JOZq2R3jOWCAyFkIqPXW96sjfnjsLCKFVzsuYrKJZfxJUSEHJLNDcG4cfxuGAV6dzIPwZpwgbQ8h8I1iQHzJ1pMj6q4BbGn4Tklt09DD8++5HpA7Qey7EolIotgrc9oHYnky4D4G58uY5OK0jW7eUogV1QlVzwvKjvYK0sliXY8C78DyYli0ma9RpuLC03pghmZZRikF4ZJWN217dP9g38tOJEEvUbO+F4eAnFdX/36H9rPnqAwqZQSQ+D5rRkldk+Gr7qYzXFDSrLJFben9E32R4OY07+81s+X41T5bWSCe4n2wgp41txlwFpsXOLk2eNPXD1o4JiLpKUitRAxBAFd5Hbu6BZJpijErnFb6mkXbaRPK47AYWERh8MfzLQErstJijGSfiDtoX701l8q0KBX7uvI7/Vl61qgp7iylvKi9xZu824SOkYb39a3duj+kFFVkgMPieWpB2Ul1SGR1P04NNye/U+emdzWzl0n5vmqLNAkpJEI9EZ6at6cdjYZ45sWos6sikPpl0ZZxvSrMoaVUu0H2p97GlqKTaERRliZOevSj5RdI8Xi0r8l+oJH3gNGEt3NSjKBtdzrcr9EvvYc=
  - secure: i4OuZ6QerSHAilw+NjW16HZelCbiaSi8gF30S4MgeqY8Ncz/GboJGpOzmq7PvbClmoT2pYUps1uOGZrXI/JKvTjFen5FS8r1Qz7zmxa64Jm84GmNDBZFZzPIncIQeoi1auuoY84F5eoQyVHFgfYsAQzmz3SoBbNfw7pyyoQLuwMdVaB09wdrKnSbKdnbgfzOMXJwTDqIvbYKYnwWvfSvqiBq5jVNI93/Bs1bHchLMpccLv5U49TgIv8jVCwswoXJLUd/eI5g29dXfWVSnCJeESrmSW1e1SkGGn3VBkRzJKPTTkcMZ4jvCodscsBxwhZf6OzLgQ41t8bPj8e9kuVEoSD5uzTeR2Rj8ojUWMRfVsoQKfJ+RDfm3/nlFEaHMMPVXryap/h6kTjgU2AkvefhI791FB63+c/ZAdvcW83pnEmt8kL/95iwWkqRSo8CPo/fUUPe/eDVWuKLGzSaLWJJ1hx7xGue9N438tujNw9Ls7YIMZIvavNkCAvrrJSQbWNWCBd9vs6AvdoYz/lMMrIW9IEwwa2CvKGNn8EPJOybBtwHxpzwW1jLK1EW0FZaF+ewLe0VRta2Xdb+52PKmdjX/wXdiadycGjTukP9e1NYlisYvekFsiWxC6NYl1TSYJCKPOp7Hk5DbmxxwhO7B3AtLPT73Q2RD9EsrJ4f+JE08os=
