language: python
python:
  - 3.6

install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install pylint

script:
  - python -m unittest discover
  - coverage erase
  - coverage run test_stories.py && coverage html
  - pylint --output-format=text stories.py

after_success:
  - codecov