language: python
python:
  - 3.6

install:
  - pip install -r requirements.txt
  - pip install codecov

script:
  - python -m unittest tests/test_stories.py
  - coverage erase
  - coverage run tests/test_stories.py

after_success:
  - codecov