#!/bin/bash
function UNITTEST()
{
	pytest
}

function APITEST()
{
	INTEGRATION_TESTS_HOST=$1 pytest integration/integration_tests.py
}

case $1 in
	unit)
		UNITTEST
		;;
	api)
		shift
		APITEST $1
		;;
	all)
		UNITTEST
		APITEST 'local'
		;;
	*)
		printf "usage:\n(./this) unit --> run unit tests\n"
		printf "(./this) api local --> run API tests against 'local' or 'heroku' according to next argument\n"
		printf "(./this) all --> run unit, then api local tests in said order\n"
		exit 1;
esac


