STORY_REACTION_LIKE = "like"
STORY_REACTION_DISLIKE = "dislike"
STORY_REACTION_FUNNY = "funny"
STORY_REACTION_BORING = "boring"

ALLOWED_STORY_REACTIONS = {STORY_REACTION_BORING, STORY_REACTION_DISLIKE, STORY_REACTION_FUNNY, STORY_REACTION_LIKE}